services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
    depends_on:
      redis:
        condition: service_started
    command: npm run dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "bridge"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: