services:
  heritrace-dataset:
    image: arcangelo7/heritrace-testing-virtuoso-dataset:1.0.2
    container_name: heritrace-dataset
    ports:
      - "8890:8890"
    environment:
      - DBA_PASSWORD=dba
      - DAV_PASSWORD=dba
      - CONTAINER_TYPE=dataset

    volumes:
      - ./dataset_database:/database
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8890/sparql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - heritrace-network

  heritrace-provenance:
    image: arcangelo7/heritrace-testing-virtuoso-provenance:1.0.2
    container_name: heritrace-provenance
    ports:
      - "8891:8890"
    environment:
      - DBA_PASSWORD=dba
      - DAV_PASSWORD=dba
      - CONTAINER_TYPE=provenance

    volumes:
      - ./prov_database:/database
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8890/sparql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - heritrace-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "6379:6379"  # Redis port for development
    environment:
      # Application Configuration
      - FLASK_ENV=demo
      - APP_TITLE=HERITRACE
      - APP_SUBTITLE=A semantic editor for heritage data
      - SECRET_KEY=dev-secret-key-change-in-production
      
      # Cache Configuration
      - CACHE_VALIDITY_DAYS=7
      
      # Database Configuration
      - DATASET_DB_URL=http://heritrace-dataset:8890/sparql
      - PROVENANCE_DB_URL=http://heritrace-provenance:8890/sparql
      - DATASET_DB_TRIPLESTORE=virtuoso
      - PROVENANCE_DB_TRIPLESTORE=virtuoso
      - DATASET_DB_TEXT_INDEX_ENABLED=false
      - DATASET_IS_QUADSTORE=true
      - PROVENANCE_IS_QUADSTORE=true
      
      # ORCID Configuration (placeholder values - not used in demo mode)
      - ORCID_CLIENT_ID=your-orcid-client-id
      - ORCID_CLIENT_SECRET=your-orcid-client-secret
      - ORCID_WHITELIST=0000-0000-0000-0000
      - ORCID_AUTHORIZE_URL=https://orcid.org/oauth/authorize
      - ORCID_TOKEN_URL=https://orcid.org/oauth/token
      - ORCID_API_URL=https://pub.orcid.org/v2.1
      - ORCID_SCOPE=/authenticate
      
      # Provenance Configuration
      - DATASET_GENERATION_TIME=2024-12-25T00:00:00+00:00
      - PRIMARY_SOURCE=https://example.org
      
      # Handling Strategies
      - ORPHAN_HANDLING_STRATEGY=ASK
      - PROXY_HANDLING_STRATEGY=ASK
      
      # Component Classes
      - COUNTER_HANDLER_CLASS=default_components.meta_counter_handler.MetaCounterHandler
      - URI_GENERATOR_CLASS=default_components.meta_uri_generator.MetaURIGenerator
      
      # Development Configuration
      - BAKE=true
      - SHACL_PATH=/app/shacl.ttl
      - DISPLAY_RULES_PATH=/app/display_rules.yaml
    volumes:
      - ./heritrace:/app/heritrace
      - ./app.py:/app/app.py
      - ./default_components:/app/default_components
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./shacl.ttl:/app/shacl.ttl
      - ./display_rules.yaml:/app/display_rules.yaml
      - ./babel:/app/babel
      - ./webpack.config.js:/app/webpack.config.js
      - ./redis-data:/data
    depends_on:
      heritrace-dataset:
        condition: service_healthy
      heritrace-provenance:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - heritrace-network
      

networks:
  heritrace-network:
    driver: bridge

volumes:
  redis-data: