services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./heritrace:/app/heritrace
      - ./app.py:/app/app.py
      - ./default_components:/app/default_components
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./shacl.ttl:/app/shacl.ttl
      - ./display_rules.yaml:/app/display_rules.yaml
      - ./babel:/app/babel
      - ./webpack.config.js:/app/webpack.config.js
      - ./redis-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - heritrace-network
      

networks:
  heritrace-network:
    driver: bridge

volumes:
  redis-data: