services:
  heritrace-dataset:
    image: arcangelo7/heritrace-testing-virtuoso-dataset:1.0.1
    container_name: heritrace-dataset
    environment:
      - DBA_PASSWORD=dba
      - DAV_PASSWORD=dba
      - CONTAINER_TYPE=dataset

    volumes:
      - ./dataset_database:/database
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8890/sparql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - heritrace-network

  heritrace-provenance:
    image: arcangelo7/heritrace-testing-virtuoso-provenance:1.0.1
    container_name: heritrace-provenance
    environment:
      - DBA_PASSWORD=dba
      - DAV_PASSWORD=dba
      - CONTAINER_TYPE=provenance
 
    volumes:
      - ./prov_database:/database
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8890/sparql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - heritrace-network
    
  heritrace:
    image: arcangelo7/heritrace:2.4.1
    container_name: heritrace-app
    environment:
      # Application settings
      - FLASK_ENV=demo
      - APP_TITLE=HERITRACE
      - APP_SUBTITLE=Configurator Testing Environment
      
      # Security (using default for demo)
      - SECRET_KEY=demo-secret-key-change-in-production
      
      # Database endpoints (pointing to internal services)
      - DATASET_DB_URL=http://heritrace-dataset:8890/sparql
      - PROVENANCE_DB_URL=http://heritrace-provenance:8890/sparql
      - DATASET_DB_TRIPLESTORE=virtuoso
      - PROVENANCE_DB_TRIPLESTORE=virtuoso
      
      # Database settings
      - DATASET_DB_TEXT_INDEX_ENABLED=false
      - DATASET_IS_QUADSTORE=true
      - PROVENANCE_IS_QUADSTORE=true
                  
      # Provenance settings
      - DATASET_GENERATION_TIME=2025-07-24T00:00:00+02:00
      - PRIMARY_SOURCE=https://doi.org/10.5281/zenodo.16415791
    volumes:
      # Configuration files for customization
      - ./config/shacl.ttl:/app/shacl.ttl
      - ./config/display_rules.yaml:/app/display_rules.yaml
    ports:
      - "5000:5000"
    depends_on:
      heritrace-dataset:
        condition: service_healthy
      heritrace-provenance:
        condition: service_healthy
    networks:
      - heritrace-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  heritrace-network:
    driver: bridge